// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ben/Projects/access governance system/internal/db/repositories/proposal_repository.go
//
// Generated by this command:
//
//	mockgen -source=/Users/ben/Projects/access governance system/internal/db/repositories/proposal_repository.go -destination=/Users/ben/Projects/access governance system/internal/db/repositories/mocks/proposal_repository.go
//
// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	models "access_governance_system/internal/db/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProposalRepository is a mock of ProposalRepository interface.
type MockProposalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProposalRepositoryMockRecorder
}

// MockProposalRepositoryMockRecorder is the mock recorder for MockProposalRepository.
type MockProposalRepositoryMockRecorder struct {
	mock *MockProposalRepository
}

// NewMockProposalRepository creates a new mock instance.
func NewMockProposalRepository(ctrl *gomock.Controller) *MockProposalRepository {
	mock := &MockProposalRepository{ctrl: ctrl}
	mock.recorder = &MockProposalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProposalRepository) EXPECT() *MockProposalRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProposalRepository) Create(request *models.Proposal) (*models.Proposal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", request)
	ret0, _ := ret[0].(*models.Proposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProposalRepositoryMockRecorder) Create(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProposalRepository)(nil).Create), request)
}

// Delete mocks base method.
func (m *MockProposalRepository) Delete(request *models.Proposal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", request)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProposalRepositoryMockRecorder) Delete(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProposalRepository)(nil).Delete), request)
}

// GetManyByNomineeNickname mocks base method.
func (m *MockProposalRepository) GetManyByNomineeNickname(nomineeNickName string) ([]*models.Proposal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManyByNomineeNickname", nomineeNickName)
	ret0, _ := ret[0].([]*models.Proposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManyByNomineeNickname indicates an expected call of GetManyByNomineeNickname.
func (mr *MockProposalRepositoryMockRecorder) GetManyByNomineeNickname(nomineeNickName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManyByNomineeNickname", reflect.TypeOf((*MockProposalRepository)(nil).GetManyByNomineeNickname), nomineeNickName)
}

// GetManyByStatus mocks base method.
func (m *MockProposalRepository) GetManyByStatus(status ...models.ProposalStatus) ([]*models.Proposal, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range status {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetManyByStatus", varargs...)
	ret0, _ := ret[0].([]*models.Proposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManyByStatus indicates an expected call of GetManyByStatus.
func (mr *MockProposalRepositoryMockRecorder) GetManyByStatus(status ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManyByStatus", reflect.TypeOf((*MockProposalRepository)(nil).GetManyByStatus), status...)
}

// GetOneByID mocks base method.
func (m *MockProposalRepository) GetOneByID(id int64) (*models.Proposal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByID", id)
	ret0, _ := ret[0].(*models.Proposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByID indicates an expected call of GetOneByID.
func (mr *MockProposalRepositoryMockRecorder) GetOneByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByID", reflect.TypeOf((*MockProposalRepository)(nil).GetOneByID), id)
}

// Update mocks base method.
func (m *MockProposalRepository) Update(request *models.Proposal) (*models.Proposal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", request)
	ret0, _ := ret[0].(*models.Proposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProposalRepositoryMockRecorder) Update(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProposalRepository)(nil).Update), request)
}
