// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ben/Projects/access governance system/internal/db/repositories/user_repository.go
//
// Generated by this command:
//
//	mockgen -source=/Users/ben/Projects/access governance system/internal/db/repositories/user_repository.go -destination=/Users/ben/Projects/access governance system/internal/db/repositories/mocks/user_repository.go
//
// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	models "access_governance_system/internal/db/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(request *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", request)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), request)
}

// GetManyByRole mocks base method.
func (m *MockUserRepository) GetManyByRole(role models.UserRole) ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManyByRole", role)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManyByRole indicates an expected call of GetManyByRole.
func (mr *MockUserRepositoryMockRecorder) GetManyByRole(role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManyByRole", reflect.TypeOf((*MockUserRepository)(nil).GetManyByRole), role)
}

// GetOneByID mocks base method.
func (m *MockUserRepository) GetOneByID(id int) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByID", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByID indicates an expected call of GetOneByID.
func (mr *MockUserRepositoryMockRecorder) GetOneByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByID", reflect.TypeOf((*MockUserRepository)(nil).GetOneByID), id)
}

// GetOneByTelegramID mocks base method.
func (m *MockUserRepository) GetOneByTelegramID(telegramID int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByTelegramID", telegramID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByTelegramID indicates an expected call of GetOneByTelegramID.
func (mr *MockUserRepositoryMockRecorder) GetOneByTelegramID(telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByTelegramID", reflect.TypeOf((*MockUserRepository)(nil).GetOneByTelegramID), telegramID)
}

// GetOneByTelegramNickname mocks base method.
func (m *MockUserRepository) GetOneByTelegramNickname(telegramNickname string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByTelegramNickname", telegramNickname)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByTelegramNickname indicates an expected call of GetOneByTelegramNickname.
func (mr *MockUserRepositoryMockRecorder) GetOneByTelegramNickname(telegramNickname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByTelegramNickname", reflect.TypeOf((*MockUserRepository)(nil).GetOneByTelegramNickname), telegramNickname)
}

// Update mocks base method.
func (m *MockUserRepository) Update(request *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", request)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), request)
}
