// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ben/Projects/access governance system/internal/services/vote_service.go
//
// Generated by this command:
//
//	mockgen -source=/Users/ben/Projects/access governance system/internal/services/vote_service.go -destination=/Users/ben/Projects/access governance system/internal/services/mocks/vote_service.go
//
// Package mock_services is a generated GoMock package.
package mock_services

import (
	models "access_governance_system/internal/db/models"
	services "access_governance_system/internal/services"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockVoteService is a mock of VoteService interface.
type MockVoteService struct {
	ctrl     *gomock.Controller
	recorder *MockVoteServiceMockRecorder
}

// MockVoteServiceMockRecorder is the mock recorder for MockVoteService.
type MockVoteServiceMockRecorder struct {
	mock *MockVoteService
}

// NewMockVoteService creates a new mock instance.
func NewMockVoteService(ctrl *gomock.Controller) *MockVoteService {
	mock := &MockVoteService{ctrl: ctrl}
	mock.recorder = &MockVoteServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVoteService) EXPECT() *MockVoteServiceMockRecorder {
	return m.recorder
}

// CreatePoll mocks base method.
func (m *MockVoteService) CreatePoll(title, description string, dueDate time.Time) (models.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePoll", title, description, dueDate)
	ret0, _ := ret[0].(models.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePoll indicates an expected call of CreatePoll.
func (mr *MockVoteServiceMockRecorder) CreatePoll(title, description, dueDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePoll", reflect.TypeOf((*MockVoteService)(nil).CreatePoll), title, description, dueDate)
}

// GetVotes mocks base method.
func (m *MockVoteService) GetVotes(pollID int) ([]services.Vote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVotes", pollID)
	ret0, _ := ret[0].([]services.Vote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVotes indicates an expected call of GetVotes.
func (mr *MockVoteServiceMockRecorder) GetVotes(pollID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVotes", reflect.TypeOf((*MockVoteService)(nil).GetVotes), pollID)
}
